# test_deploy_scaffold.lex — #188: deterministic TLS deploy scaffolding.
#
# The property under test: the bytes that reach the server are pure-function
# output with the safety-relevant choices baked in — pinned Caddy major,
# restart policy, read-only Caddyfile mount, TLS front door as the health
# URL when a domain is declared — and no secret material anywhere in a
# generated artifact. The exact-string regressions live in the modules'
# examples {} blocks; these tests assert the structural contract so a
# future edit can reshape the YAML without rewriting byte-for-byte
# literals here.

import "std.io" as io

import "std.list" as list

import "std.str" as str

import "../src/deploy_scaffold" as scaffold

fn check(name :: Str, cond :: Bool) -> Result[Unit, Str] {
  if cond {
    Ok(())
  } else {
    Err(name)
  }
}

fn test_compose_shape() -> Result[Unit, Str] {
  let yml := scaffold.compose_yaml("widgetapi", 9000)
  let pinned := str.contains(yml, "image: caddy:2") and str.contains(yml, "latest") == false
  let restart := str.contains(yml, "restart: unless-stopped")
  let named := str.contains(yml, "container_name: widgetapi")
  let published := str.contains(yml, "\"9000:9000\"")
  let tls_ports := str.contains(yml, "\"80:80\"") and str.contains(yml, "\"443:443\"")
  let ro_mount := str.contains(yml, "./Caddyfile:/etc/caddy/Caddyfile:ro")
  let cert_volume := str.contains(yml, "caddy_data:/data")
  check("compose has pinned caddy, restart policy, ro Caddyfile mount, cert volume", pinned and restart and named and published and tls_ports and ro_mount and cert_volume)
}

fn test_caddyfile_routes_domain_to_app() -> Result[Unit, Str] {
  let cf := scaffold.caddyfile("widgets.example.com", 9000)
  check("Caddyfile opens a domain block proxying to app:port", str.contains(cf, "widgets.example.com {") and str.contains(cf, "reverse_proxy app:9000"))
}

# The health URL is the deploy's proof obligation: with a domain it MUST be
# the https front door (a green check through the raw port would say
# nothing about the certificate), without one it stays the v1 host:port.
fn test_health_url_is_tls_front_door_when_domain_set() -> Result[Unit, Str] {
  let with_domain := scaffold.health_url("widgets.example.com", "203.0.113.7", 9000, "/health")
  let without := scaffold.health_url("", "203.0.113.7", 9000, "/health")
  check("domain => https://domain, no domain => http://host:port", with_domain == "https://widgets.example.com/health" and without == "http://203.0.113.7:9000/health")
}

fn test_remote_up_is_idempotent_compose() -> Result[Unit, Str] {
  let cmd := scaffold.remote_up_command("/opt/loom-deploys/widgetapi")
  check("remote command is compose up -d --build in the remote dir", str.contains(cmd, "cd /opt/loom-deploys/widgetapi") and str.contains(cmd, "docker compose up -d --build"))
}

# Quoted heredoc: the sentinel is single-quoted so generated bytes are
# taken literally (no shell expansion), and content is normalized to end
# with a newline so the closing sentinel sits on its own line.
fn test_write_file_cmd_uses_quoted_heredoc() -> Result[Unit, Str] {
  let cmd := scaffold.write_file_cmd("/w/docker-compose.yml", "a: $HOME\n")
  let quoted := str.contains(cmd, "<<'LOOM_SCAFFOLD_EOF'")
  let literal_body := str.contains(cmd, "a: $HOME\n")
  let closed := str.ends_with(cmd, "\nLOOM_SCAFFOLD_EOF\n")
  let normalized := str.ends_with(scaffold.write_file_cmd("/w/f", "no-newline"), "no-newline\nLOOM_SCAFFOLD_EOF\n")
  check("quoted heredoc, literal body, closing sentinel on its own line", quoted and literal_body and closed and normalized)
}

# No generated artifact may carry credentials: server access lives in the
# operator's HETZNER_* environment, never in the files rsynced to the box.
fn test_no_secret_material_in_artifacts() -> Result[Unit, Str] {
  let all := str.join([scaffold.compose_yaml("widgetapi", 9000), scaffold.caddyfile("widgets.example.com", 9000), scaffold.remote_up_command("/opt/loom-deploys/widgetapi")], "\n")
  let no_ssh := str.contains(all, "ssh") == false
  let no_env_names := str.contains(all, "HETZNER") == false and str.contains(all, "SSH_KEY") == false
  let no_key_blocks := str.contains(all, "PRIVATE KEY") == false
  check("no ssh material, env names, or key blocks in generated files", no_ssh and no_env_names and no_key_blocks)
}

fn suite() -> List[Result[Unit, Str]] {
  [test_compose_shape(), test_caddyfile_routes_domain_to_app(), test_health_url_is_tls_front_door_when_domain_set(), test_remote_up_is_idempotent_compose(), test_write_file_cmd_uses_quoted_heredoc(), test_no_secret_material_in_artifacts()]
}

fn run_all() -> [io] Unit {
  let results := suite()
  let __dbg := list.map(results, fn (r :: Result[Unit, Str]) -> [io] Unit {
    match r {
      Ok(_) => (),
      Err(e) => io.print(str.concat("FAIL: ", e)),
    }
  })
  let failures := list.fold(results, 0, fn (n :: Int, r :: Result[Unit, Str]) -> Int {
    match r {
      Ok(_) => n,
      Err(_) => n + 1,
    }
  })
  if failures == 0 {
    ()
  } else {
    let __force_fail := 1 / 0
    ()
  }
}

