# consortium_main.lex -- the consortium's phases as commands (run 1,
# docs/consortium-freeze.md). Every command is driven by environment
# variables, like main.lex's, and bin/consortium-run.sh is the human-facing
# wrapper:
#
#   CONSORTIUM_DB=... PROBLEM_SPACE=... [RESEARCHCO_MANIFEST=...] consortium_open_cmd
#   CONSORTIUM_DB=... REPORT_DIR=... [LOOM_SEARCH_LEDGER=...]     consortium_deliver_cmd
#   CONSORTIUM_DB=... ANSWER=yes|no [NOTE=...]                    consortium_answer_cmd
#   CONSORTIUM_DB=... REPORT_PATH=... [SOFTWARECO_MANIFEST=...]  consortium_open_software_cmd
#   CONSORTIUM_DB=... COMPANY_DB=... WORKSPACE_DIR=...            consortium_deliver_software_cmd
#   CONSORTIUM_DB=...                                             consortium_status_cmd
#
# lex-economy writes its money events to a lex-trail log; that log lives in
# <CONSORTIUM_DB>.trail, a separate file, because lex-trail's schema and
# loom's share a table name (attestations) with different columns.
#
# deliver runs the SAME checker the supplier's gate ran
# (bin/check_research_report.py, against the same search ledger) and hands
# its output to the controller: the buyer re-derives the evidence rather
# than trusting the supplier's word that its gate passed.

import "std.env" as env

import "std.io" as io

import "std.str" as str

import "std.time" as time

import "std.process" as proc

import "std.int" as int

import "lex-orm/src/connection" as conn

import "lex-trail/src/log" as tlog

import "lex-economy/src/contract" as contract

import "./migrate" as migrate

import "./consortium" as cs

fn get_env(key :: Str, default :: Str) -> [env] Str {
  match env.get(key) {
    None => default,
    Some(v) => if str.is_empty(v) {
      default
    } else {
      v
    },
  }
}

fn default_problem_space() -> Str {
  "paid micro-APIs for solo developers who need to validate and normalise user-submitted data (addresses, phone numbers, CSV uploads, free-text dates)"
}

fn open_db(path :: Str) -> [sql, fs_write] Result[(conn.ConnDb, tlog.Log), Str] {
  match conn.open(path) {
    Err(_) => Err(str.concat("consortium: cannot open ", path)),
    Ok(db) => match migrate.run(db.handle) {
      Err(e) => Err(str.concat("consortium: migrate: ", e)),
      Ok(_) => match tlog.open(str.concat(path, ".trail")) {
        Err(e) => Err(str.concat("consortium: trail log: ", e)),
        Ok(log) => Ok((db, log)),
      },
    },
  }
}

fn toml_str(s :: Str) -> Str {
  str.replace(str.replace(s, "\\", "\\\\"), "\"\"\"", "\\\"\"\"")
}

# The ResearchCo manifest bootstrap consumes: the contract's goal is the
# mission, the packs are core + research, the path is the document path.
fn researchco_manifest(goal :: Str, model :: Str) -> Str {
  str.join(["# Generated by consortium_open_cmd from the awarded research contract.\n", "# The mission IS the contract: its criteria are the ones settlement will use.\n\n", "[identity]\n", "id      = \"", cs.researchco(), "\"\n", "name    = \"ResearchCo\"\n", "mission = \"\"\"", toml_str(goal), "\"\"\"\n\n", "[stack]\n", "path  = \"research-report\"\n", "model = \"", model, "\"\n\n", "[roles]\n", "packs = [\"core\", \"research\"]\n\n", "[policy]\n", "max_iterations = 3\n", "budget_eur     = 1\n"], "")
}

fn consortium_open_cmd() -> [env, io, sql, time, fs_read, fs_write] Unit {
  let db_path := get_env("CONSORTIUM_DB", "consortium.db")
  let problem := get_env("PROBLEM_SPACE", default_problem_space())
  let manifest_path := get_env("RESEARCHCO_MANIFEST", "")
  let model := get_env("MODEL", "")
  if str.is_empty(model) {
    io.print(model_required_msg())
  } else {
    match open_db(db_path) {
      Err(e) => io.print(str.concat("[consortium] FATAL: ", e)),
      Ok((db, log)) => match cs.open_run(db, log, problem, time.now_ms()) {
        Err(e) => io.print(str.concat("[consortium] open FAILED: ", e)),
        Ok(o) => {
          let __p := io.print(str.join(["[consortium] contract ", o.contract.id, " awarded: ", o.contract.buyer, " buys ", cs.research_capability(), " from ", o.contract.supplier, " for ", int_str(o.contract.price.cents), "c (", o.reason, ")"], ""))
          let __m := if str.is_empty(manifest_path) {
            ()
          } else {
            let __w := io.write(manifest_path, researchco_manifest(o.goal, model))
            io.print(str.concat("[consortium] ResearchCo manifest written: ", manifest_path))
          }
          let __g := io.print(str.concat("[consortium] goal for ResearchCo:\n", o.goal))
          io.print(cs.status_text(db, time.now_ms()))
        },
      },
    }
  }
}

# There is no default model anywhere in loom any more. Forgetting to name
# one used to run somebody else's model on somebody's key, under a name the
# operator never chose -- the same failure #427 removed for providers.
fn model_required_msg() -> Str {
  "[consortium] FATAL: MODEL is not set, and there is no default model. Name it explicitly, e.g. MODEL=kimi-k2.7-code"
}

fn int_str(n :: Int) -> Str {
  int.to_str(n)
}

# The SoftwareCo manifest: the software contract's goal (which carries the
# settled report) is the mission; the proven python-fastapi path; core pack.
fn softwareco_manifest(goal :: Str, model :: Str) -> Str {
  str.join(["# Generated by consortium_open_software_cmd from the awarded software contract.\n", "# The mission IS the contract: its criteria are the ones settlement will use.\n\n", "[identity]\n", "id      = \"", cs.softwareco(), "\"\n", "name    = \"SoftwareCo\"\n", "mission = \"\"\"", toml_str(goal), "\"\"\"\n\n", "[stack]\n", "path  = \"python-fastapi\"\n", "model = \"", model, "\"\n\n", "[roles]\n", "packs = [\"core\"]\n\n", "[policy]\n", "max_iterations = 3\n", "budget_eur     = 25\n"], "")
}

# The SoftwareCo manifest for the operable phase: same company, same path,
# plus the packs whose roles produce the contract's evidence.
fn softwareco_operable_manifest(goal :: Str, model :: Str) -> Str {
  str.join(["# Generated by consortium_open_operable_cmd from the awarded operable contract.\n", "# The mission IS the contract: its criteria are the ones settlement will use.\n\n", "[identity]\n", "id      = \"", cs.softwareco(), "\"\n", "name    = \"SoftwareCo\"\n", "mission = \"\"\"", toml_str(goal), "\"\"\"\n\n", "[stack]\n", "path  = \"python-fastapi\"\n", "model = \"", model, "\"\n\n", "[roles]\n", "packs = [\"core\", \"ops\", \"governance\"]\n\n", "[policy]\n", "max_iterations = 3\n", "budget_eur     = 25\n"], "")
}

fn consortium_open_operable_cmd() -> [env, io, sql, time, fs_read, fs_write] Unit {
  let db_path := get_env("CONSORTIUM_DB", "consortium.db")
  let manifest_path := get_env("OPERABLE_MANIFEST", "")
  let model := get_env("MODEL", "")
  if str.is_empty(model) {
    io.print(model_required_msg())
  } else {
    match open_db(db_path) {
      Err(e) => io.print(str.concat("[consortium] FATAL: ", e)),
      Ok((db, log)) => match cs.open_operable(db, log, time.now_ms()) {
        Err(e) => io.print(str.concat("[consortium] open-operable FAILED: ", e)),
        Ok(o) => {
          let __p := io.print(str.join(["[consortium] contract ", o.contract.id, " awarded: ", o.contract.buyer, " makes ", cs.operable_capability(), " itself for ", int_str(o.contract.price.cents), "c (", o.reason, ")"], ""))
          let __m := if str.is_empty(manifest_path) {
            ()
          } else {
            let __w := io.write(manifest_path, softwareco_operable_manifest(o.goal, model))
            io.print(str.concat("[consortium] SoftwareCo operable manifest written: ", manifest_path))
          }
          io.print(cs.status_text(db, time.now_ms()))
        },
      },
    }
  }
}

# deliver-operable: the buyer re-derives the evidence with the composite
# checker. DEPLOY_DOMAIN, when set, lets it assess reachable-over-tls; absent,
# that criterion is unmet and the contract settles at 50% by the same rule as
# every other partial delivery.
fn consortium_deliver_operable_cmd() -> [env, io, sql, time, fs_read, fs_write, proc] Unit {
  let db_path := get_env("CONSORTIUM_DB", "consortium.db")
  let company_db := get_env("COMPANY_DB", "")
  let ws := get_env("WORKSPACE_DIR", "")
  let domain := get_env("DEPLOY_DOMAIN", "")
  if str.is_empty(company_db) or str.is_empty(ws) {
    io.print("[consortium] FATAL: COMPANY_DB and WORKSPACE_DIR are required (SoftwareCo's company.db and workspace)")
  } else {
    let args := if str.is_empty(domain) {
      ["bin/check_operable_delivery.py", company_db, ws]
    } else {
      ["bin/check_operable_delivery.py", company_db, ws, "--domain", domain]
    }
    match proc.run("python3", args) {
      Err(m) => io.print(str.concat("[consortium] FATAL: the checker could not run: ", m)),
      Ok(r) => {
        let output := str.concat(r.stdout, r.stderr)
        let __c := io.print(str.concat("[consortium] checker said:\n", str.trim(output)))
        match open_db(db_path) {
          Err(e) => io.print(str.concat("[consortium] FATAL: ", e)),
          Ok((db, log)) => match cs.deliver(db, log, cs.operable_contract_id(), output, time.now_ms()) {
            Err(e) => io.print(str.concat("[consortium] deliver-operable FAILED: ", e)),
            Ok(o) => {
              let __v := io.print(str.join(["[consortium] contract ", o.final.id, " ", cs.state_str(o.final.state), ": ", cs.verdict_words(o.verdict)], ""))
              io.print(cs.status_text(db, time.now_ms()))
            },
          },
        }
      },
    }
  }
}

fn consortium_open_software_cmd() -> [env, io, sql, time, fs_read, fs_write] Unit {
  let db_path := get_env("CONSORTIUM_DB", "consortium.db")
  let report_path := get_env("REPORT_PATH", "")
  let manifest_path := get_env("SOFTWARECO_MANIFEST", "")
  let model := get_env("MODEL", "")
  if str.is_empty(model) {
    io.print(model_required_msg())
  } else {
    if str.is_empty(report_path) {
      io.print("[consortium] FATAL: REPORT_PATH is required (the settled report.md)")
    } else {
      match io.read(report_path) {
        Err(_) => io.print(str.concat("[consortium] FATAL: cannot read ", report_path)),
        Ok(report) => match open_db(db_path) {
          Err(e) => io.print(str.concat("[consortium] FATAL: ", e)),
          Ok((db, log)) => match cs.open_software(db, log, report, time.now_ms()) {
            Err(e) => io.print(str.concat("[consortium] open-software FAILED: ", e)),
            Ok(o) => {
              let __p := io.print(str.join(["[consortium] contract ", o.contract.id, " awarded: ", o.contract.buyer, " builds ", cs.software_capability(), " itself for ", int_str(o.contract.price.cents), "c (", o.reason, ")"], ""))
              let __m := if str.is_empty(manifest_path) {
                ()
              } else {
                let __w := io.write(manifest_path, softwareco_manifest(o.goal, model))
                io.print(str.concat("[consortium] SoftwareCo manifest written: ", manifest_path))
              }
              io.print(cs.status_text(db, time.now_ms()))
            },
          },
        },
      }
    }
  }
}

fn consortium_deliver_software_cmd() -> [env, io, sql, time, fs_read, fs_write, proc] Unit {
  let db_path := get_env("CONSORTIUM_DB", "consortium.db")
  let company_db := get_env("COMPANY_DB", "")
  let ws := get_env("WORKSPACE_DIR", "")
  if str.is_empty(company_db) or str.is_empty(ws) {
    io.print("[consortium] FATAL: COMPANY_DB and WORKSPACE_DIR are required (SoftwareCo's company.db and workspace)")
  } else {
    match proc.run("python3", ["bin/check_software_delivery.py", company_db, ws]) {
      Err(m) => io.print(str.concat("[consortium] FATAL: the checker could not run: ", m)),
      Ok(r) => {
        let output := str.concat(r.stdout, r.stderr)
        let __c := io.print(str.concat("[consortium] checker said:\n", str.trim(output)))
        match open_db(db_path) {
          Err(e) => io.print(str.concat("[consortium] FATAL: ", e)),
          Ok((db, log)) => match cs.deliver(db, log, cs.software_contract_id(), output, time.now_ms()) {
            Err(e) => io.print(str.concat("[consortium] deliver-software FAILED: ", e)),
            Ok(o) => {
              let __v := io.print(str.join(["[consortium] contract ", o.final.id, " ", cs.state_str(o.final.state), ": ", cs.verdict_words(o.verdict)], ""))
              io.print(cs.status_text(db, time.now_ms()))
            },
          },
        }
      },
    }
  }
}

fn checker_script(report_dir :: Str, ledger :: Str) -> Str {
  str.join(["ROOT=\"$PWD\"; cd '", report_dir, "' && LOOM_SEARCH_LEDGER='", ledger, "' python3 \"$ROOT/bin/check_research_report.py\" . 2>&1"], "")
}

fn consortium_deliver_cmd() -> [env, io, sql, time, fs_read, fs_write, proc] Unit {
  let db_path := get_env("CONSORTIUM_DB", "consortium.db")
  let contract_id := get_env("CONTRACT_ID", cs.research_contract_id())
  let report_dir := get_env("REPORT_DIR", "")
  let ledger := get_env("LOOM_SEARCH_LEDGER", str.join(["/tmp/loom-search-ledger-", cs.researchco(), ".txt"], ""))
  if str.is_empty(report_dir) {
    io.print("[consortium] FATAL: REPORT_DIR is required (the directory holding the delivered report.md)")
  } else {
    match proc.run("bash", ["-c", checker_script(report_dir, ledger)]) {
      Err(m) => io.print(str.concat("[consortium] FATAL: the checker could not run: ", m)),
      Ok(r) => {
        let output := str.concat(r.stdout, r.stderr)
        let __c := io.print(str.concat("[consortium] checker said:\n", str.trim(output)))
        match open_db(db_path) {
          Err(e) => io.print(str.concat("[consortium] FATAL: ", e)),
          Ok((db, log)) => match cs.deliver(db, log, contract_id, output, time.now_ms()) {
            Err(e) => io.print(str.concat("[consortium] deliver FAILED: ", e)),
            Ok(o) => {
              let __v := io.print(str.join(["[consortium] contract ", o.final.id, " ", cs.state_str(o.final.state), ": ", cs.verdict_words(o.verdict)], ""))
              let __q := match o.verdict {
                Ambiguous(_) => io.print(str.join(["[consortium] QUESTION FOR THE FOUNDER (", cs.human_attr(), "): Is the recommended opportunity one you would fund? Answer with:\n  ANSWER=yes|no NOTE='...' bin/consortium-run.sh answer"], "")),
                _ => (),
              }
              io.print(cs.status_text(db, time.now_ms()))
            },
          },
        }
      },
    }
  }
}

fn consortium_answer_cmd() -> [env, io, sql, time, fs_write] Unit {
  let db_path := get_env("CONSORTIUM_DB", "consortium.db")
  let contract_id := get_env("CONTRACT_ID", cs.research_contract_id())
  let ans := str.to_lower(get_env("ANSWER", ""))
  let note := get_env("NOTE", "")
  if ans != "yes" and ans != "no" {
    io.print("[consortium] FATAL: ANSWER must be yes or no")
  } else {
    match open_db(db_path) {
      Err(e) => io.print(str.concat("[consortium] FATAL: ", e)),
      Ok((db, log)) => match cs.answer(db, log, contract_id, ans == "yes", note, time.now_ms()) {
        Err(e) => io.print(str.concat("[consortium] answer FAILED: ", e)),
        Ok(o) => {
          let __v := io.print(str.join(["[consortium] contract ", o.final.id, " ", cs.state_str(o.final.state), ": ", cs.verdict_words(o.verdict)], ""))
          io.print(cs.status_text(db, time.now_ms()))
        },
      },
    }
  }
}

fn consortium_status_cmd() -> [env, io, sql, time, fs_write] Unit {
  let db_path := get_env("CONSORTIUM_DB", "consortium.db")
  match open_db(db_path) {
    Err(e) => io.print(str.concat("[consortium] FATAL: ", e)),
    Ok((db, _log)) => io.print(cs.status_text(db, time.now_ms())),
  }
}

